### ISSUE TITLE
Life

### ISSUE THREAD

**Issue by rc2000123** [atvaccaro/CopperMod#1]
add life plz

**Comment by atvaccaro** [comment]
What do you mean "add life"?

**Comment by C0de-Ninja** [comment]
@atvaccaro Whats your problem dude? You don't know what add life means? Dang, i thought EVERYONE knew that :laughing:

**Comment by rc2000123** [comment]
[image: Inline image 1]
yea its OBVIOUSLY a detailed paint service company.....right?

**Comment by atvaccaro** [comment]
I'm confused.
